export interface Pharmacy {
  website: string,
  sub_type: string,
  postcode: string,
  phone: string,
  partial_postcode: string,
  parent_o_d_s_code: string,
  parent_name: string,
  organisation_type: string,
  organisation_status: string,
  organisation_name: string,
  organisation_id: string,
  organisation_code: string,
  longitude: string,
  latitude: string,
  is_pims_managed: string,
  is_e_p_s_enabled: string,
  fax: string,
  email: string,
  county: string,
  city: string,
  address3: string,
  address2: string,
  address1: string
}
